- hosts: redhat
  vars_files: 
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"

  tasks:
      - name: Installing software
        package:
              name: "{{ software_name }}"
              state: present

      - name: Copy index.html file
        template:
            dest: "{{doc_root}}/index.html"
            src: /root/Ansible/ws11/index.html
        
      - name: Stating service
        service:
             name: "{{service_name}}"
             state: started  





